### ISSUE TITLE
Allow API implementations to handle errors

### ISSUE THREAD

**Issue by stuntguy3000** [JavaTelegramBot-API/JavaTelegramBot-API#12]
By printing errors to console, it means API implementations cannot properly handle any errors. 

My suggestions are to either throw an exception, or have a onError event for the implementation to listen for.

**Comment by aaomidi** [comment]
onErrorEvent is a bad idea.

Exceptions are made for this. +1 for Exceptions.

**Comment by zackpollard** [comment]
This will be implemented in one of the coming updates, it is something I have intended to do from the very beginning but I personally believed getting a full bug free implementation was important first. Will update this once this has been implemented.

**Comment by nickrobson** [comment]
easy fix for the mean time: override System.err, find error messages, handle??

**Comment by mkotb** [comment]
it's been over a year, zack.

**Comment by mkotb** [comment]
little over a month to two years!!!

**Comment by bo0tzz** [comment]
@mkotb Lmfao

**Comment by stuntguy3000** [comment]
noice

**Comment by wrxck** [comment]
@stuntguy3000 luke why did you leave telegram we all miss you!!!

**Comment by stuntguy3000** [comment]
I had my reasons and I stick by them

**Comment by zackpollard** [comment]
@stuntguy3000 It's ok, we're glad you're gone really

**Comment by YoloxPanda** [comment]
xDxDddxDxd

**Comment by stuntguy3000** [comment]
You deserved it

**Comment by stuntguy3000** [comment]
Same tbh @zackpollard

**Comment by nickrobson** [comment]
@stuntguy3000 why so salty

**Comment by stuntguy3000** [comment]
![image](https://user-images.githubusercontent.com/1522389/31856576-2fbd7eec-b70c-11e7-8e83-32c9e6d82248.png)

**Comment by stuntguy3000** [comment]
Censorship!!11
