### ISSUE TITLE
Implement a better way of clearing previous messages

### ISSUE THREAD

**Issue by zackpollard** [JavaTelegramBot-API/JavaTelegramBot-API#19]
Currently, the update system checks the current system date against the message sent date when it initially starts. This is fine apart from the fact that if system time is ahead by a minute or so, no messages will be received by the bot until then.

**Comment by zackpollard** [comment]
Instead of comparing messages to server unix time against the message received time, simply check to see how many messages the update response contains, and if it is less than the max, make that the last ignored update object.

**Comment by stuntguy3000** [comment]
Very happy that @zackpollard made this project come back after abandoning it. Thanks!
