### ISSUE TITLE
Incorrect encoding for caption property in some Sendable classes (Photo, Video, etc)

### ISSUE THREAD

**Issue by alebabai** [JavaTelegramBot-API/JavaTelegramBot-API#38]
There is some bug in the handling caption of photo, video, etc.
In the first time, when you send a message, that contains the caption with non-English letters, all of them are replaced by question mark.
The next message will contain the correct caption, with normal letters. Maybe it's because the file is considered to already been used, ie it is not new.
![2016-06-27 01 03 25](https://cloud.githubusercontent.com/assets/19958900/16365297/e1ed37d0-3c04-11e6-84f4-44502b5e28f3.png)
![2016-06-27 01 03 57](https://cloud.githubusercontent.com/assets/19958900/16365296/e1eb6fa4-3c04-11e6-8cff-e101b314b62f.png)

**Comment by zackpollard** [comment]
Could you please provide the code that produces this issue.

**Comment by alebabai** [comment]
For example the following code produces this issue.

``` java
                final Chat chat = event.getChat();

                try {
                    chat.sendMessage(SendablePhotoMessage
                            .builder()
                            .photo(new InputFile(new URL("http://treasure.diylol.com/uploads/post/image/916873/resized_8XTGX.jpg")))
                            .caption("Просто текст")
                            .build()
                    );
                } catch (MalformedURLException e) {
                    e.printStackTrace();
                }
```

**Comment by zackpollard** [comment]
Hey again,

I am unsure why this would happen. Do you call that exact same code twice? If so, it is probably sending the cached version of that the second time, instead of re-downloading it from the web, as my API caches all results and the telegram IDs for the files. If that is the case, I will have to take a look over the code to check there aren't any differences in the sending when using the caching code and using the URL code.

I'll try to take a look at this today and get back to you shortly

**Comment by zackpollard** [comment]
I have provided a link below to the line of code that handle adding captions to all sent photo messages. The only line that changes is the line which selects whether a File or String ID is sent. https://github.com/zackpollard/JavaTelegramBot-API/blob/ecb46def8562e083e27432425f8ff27f98e1bc97/src/main/java/pro/zackpollard/telegrambot/api/TelegramBot.java#L184-L185

**Comment by alebabai** [comment]
Hi.
Probably, this line of code explains why the caption is correct when the photo is sent a for the second time. Caption is taken from the file that is already uploaded to the server.
But this doesn't explain the problem, why the caption is incorrect for the first sending.

**Comment by zackpollard** [comment]
@alebabai The caption shouldn't be stored on the server. You can send a different caption with a cached image if you want. So that doesn't really explain the problem either.

**Comment by alebabai** [comment]
@zackpollard I tried to debug process of sending photo, but didn't understand where something goes wrong.
In [this](https://github.com/rubenlagus/TelegramBots/) tg bot api wrapper caption of photo(video, etc) is sent correctly, maybe it will help.

**Comment by zackpollard** [comment]
@alebabai If that sends it correctly, I can only assume that the library used for http interaction (unirest) is causing issues with encoding when a file is uploaded. I'll take a deeper look into this later today
