### ISSUE TITLE
No unregister for Listeners

### ISSUE THREAD

**Issue by mkhoudary** [JavaTelegramBot-API/JavaTelegramBot-API#41]
Listeners have no unregister method, especially in the EventsManager.

This causes web applications to have stuck threads and makes the library useless on application servers.

**Comment by zackpollard** [comment]
#42 is the potential fix for this issue

**Comment by mkhoudary** [comment]
Thank you!

I've cloned the repo and made the modifications myself exactly as you did, but anyway I will pull yours..

One additional thing needs to be done, I've fixed it myself but I will create an issue for you for it.. I created it as a hotfix but couldn't push it to your repo because it's protected.

**Comment by zackpollard** [comment]
If you clone the repository, then make the changes, you can then create a pull request for the modifications which I can then accept or decline. This is the standard way to contribute to open source projects on git VCS :)
