### ISSUE TITLE
Introduce simple inline menu creation

### ISSUE THREAD

**Issue by stuntguy3000** [JavaTelegramBot-API/JavaTelegramBot-API#47]
I propose a system which will allow bot developers to build interactive, slick and simple to use UI menus within Telegram's inline message system. By using the message editing functionality, bots can already use an array of callback buttons and well developed code structures to create a menu system - however the need for a centralized API is in demand. 

Creating a menu api allows menus like ones used by @RedditLiveBot's admin system (see: below). 

I would like to see a way to create a Menu, and a way to add Options. Options can link to other Menu pages, or act as a toggle switch (see: below). 

**Example Menu**
![image](https://cloud.githubusercontent.com/assets/1522389/17404211/2ca87786-5a9a-11e6-948b-b5affdb74161.png)
![image](https://cloud.githubusercontent.com/assets/1522389/17404238/34aa37e4-5a9a-11e6-84ff-8d71be3493f1.png)
![image](https://cloud.githubusercontent.com/assets/1522389/17404269/3fbd49dc-5a9a-11e6-8cc3-944ea66c6f23.png)
![image](https://cloud.githubusercontent.com/assets/1522389/17404276/453e7a0c-5a9a-11e6-8f08-ac73977dcdff.png)

**Toggle Buttons**
![image](https://cloud.githubusercontent.com/assets/1522389/17404319/67af9e54-5a9a-11e6-87ff-22d8af4592a7.png)
![image](https://cloud.githubusercontent.com/assets/1522389/17405079/4cda0c4c-5a9d-11e6-96a0-79b40fca866b.png)

@mkotb

**Comment by mkotb** [comment]
Pull request with the following features developed has been created for quite a while now and is pending acceptance.

**Comment by zackpollard** [comment]
Done with #48
