### ISSUE TITLE
Chat Instance in CallbackQuery

### ISSUE THREAD

**Issue by mkhoudary** [JavaTelegramBot-API/JavaTelegramBot-API#58]
CallbackQuery object does not contain the chat instance id

**Comment by zackpollard** [comment]
@mkhoudary Zack Pollard:
This is because there are two types of callback queries. MessageCallbackQuery and InlineMessageCallbackQuery, or something along those lines. If you use the events with those names too, you will get the correct instance of the object and can get the chat ID :)

**Comment by mkhoudary** [comment]
Thank you!
