### ISSUE TITLE
Remove incremental menu id counter

### ISSUE THREAD

**Issue by mkotb** [JavaTelegramBot-API/JavaTelegramBot-API#82]
The [incremental id system](https://github.com/zackpollard/JavaTelegramBot-API/blob/development/menus/src/main/java/pro/zackpollard/telegrambot/api/menu/internal/InlineMenuRegistryImpl.java#L29) used for menus is problematic as it resets after restarts of the bot instance. This could potentially allow a malicious client to manage other people's menus and view private information. This can be prevented by using the user predicate, however, a better idea would be to use unique ids for each menu.

**Comment by bo0tzz** [comment]
@mkotb Mfw gg
