### ISSUE TITLE
Library not working anymore on current APIs

### ISSUE THREAD

**Issue by Polve** [JavaTelegramBot-API/JavaTelegramBot-API#93]
The library stopped working, it seems like it's not able to correctly parse/send messages to current Telegram APIs

Since it seems like the project is unfortunately dead, I suppose the only option is to find other libraries.

A few links to help others with the same problem:

* https://github.com/jTelegram/jTelegramBotAPI
* https://bitbucket.org/pierpaolobaghe/spring-telegram-bot/src/master/
* https://github.com/rubenlagus/TelegramBots
* https://craftcodecrew.com/getting-started-with-the-telegram-abilitybot/

**Comment by zackpollard** [comment]
I'm going to look into why this is happening, telegram has made a breaking change to their bot API and i'm not sure why.

**Comment by Polve** [comment]
Thanks, highly appreciated, please give us some information about the process to understand if you are able to work on it or if you find some major showstoppers

**Comment by zackpollard** [comment]
It looks like they have removed the legacy "markdown" parse_mode even though it is still documented so that is returning a bad request. I will try to contact someone about this, although not sure what methods we have of doing so.

**Comment by zackpollard** [comment]
I have published a new version (1.7.1) to the github package registry. If you update your current pom.xml to the new version 1.7.1 that should pick it up. You will however need to add the following to your maven settings. For linux this is located at ~/.m2/settings.xml
```
<settings xmlns="http://maven.apache.org/SETTINGS/1.0.0"
      xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
      xsi:schemaLocation="http://maven.apache.org/SETTINGS/1.0.0
                  http://maven.apache.org/xsd/settings-1.0.0.xsd">

<activeProfiles>
    <activeProfile>github</activeProfile>
</activeProfiles>

<profiles>
    <profile>
        <id>github</id>
        <repositories>
            <repository>
                <id>central</id>
                <url>https://repo1.maven.org/maven2</url>
                <releases><enabled>true</enabled></releases>
                <snapshots><enabled>true</enabled></snapshots>
            </repository>
            <repository>
                <id>github</id>
                <name>GitHub JavaTelegramBot-API Apache Maven Packages</name>
                <url>https://maven.pkg.github.com/JavaTelegramBot-API/JavaTelegramBot-API</url>
            </repository>
        </repositories>
    </profile>
</profiles>

<servers>
    <server>
        <id>github</id>
        <username>YOUR_GITHUB_USERNAME</username>
        <password>GITHUB_PERSONAL_ACCESS_TOKEN</password>
    </server>
</servers>

</settings>
```

You will need to create a personal access token for github with read_registry permissions and replace the values in the username and password fields with your username and that personal access token.

**Comment by Polve** [comment]
Thanks!
Is the modification to settings.xml a temporary workaround or something to do in any case to use the latest version?
In this case, is possible to modify the pom.xml file instead of the personal setting in order to propagate the change to other users?

**Comment by zackpollard** [comment]
The settings.xml change is required because github registry currently doesn't support read access without authentication and it was the quickest place for me to setup a new place to push the packages to. If I pick up developing this again i'll use a registry that doesn't require authentication so this is a temporary workaround to push out a fix quickly for this issue.

**Comment by Polve** [comment]
Thanks for the explaination, but why can't you publish the new release on maven as usual?

**Comment by zackpollard** [comment]
I no longer have the CI setup or keys to publish to maven Central, so had to setup a new registry

**Comment by Polve** [comment]
Wonderful, it works!

I leave the issue open so you can update the documentation or something?
